# Generated by Django 5.1.4 on 2025-10-07 07:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0013_alter_eventregistration_guest_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, help_text='Optional override name for this department within the event.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_departments', to='Departments.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_departments', to='Events.event')),
            ],
            options={
                'ordering': ['event_id', 'department_id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sub_event', models.CharField(blank=True, max_length=120)),
                ('function_name', models.CharField(blank=True, max_length=120)),
                ('venue', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('shifts_or_days', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_rate_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax percentage (e.g., 18.0 for 18%)', max_digits=7)),
                ('markup_mode', models.CharField(choices=[('none', 'None'), ('percent', 'Percent'), ('flat', 'Flat')], default='none', max_length=10)),
                ('markup_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('invoice', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('unbilled', 'Unbilled'), ('due', 'Due'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unbilled', max_length=20)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='Departments.eventdepartment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetFieldPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.SlugField(help_text="Machine key of the field (e.g., 'unit_rate', 'vendor_name').", max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_field_perms', to=settings.AUTH_USER_MODEL)),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_field_perms', to='Departments.eventdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='EventDepartmentStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('other', 'Other')], default='viewer', max_length=20)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='Departments.eventdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_department_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_department_id', 'user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='eventdepartment',
            index=models.Index(fields=['event', 'department'], name='Departments_event_i_a2dcdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdepartment',
            unique_together={('event', 'department')},
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['event_department'], name='Departments_event_d_b989f1_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['category', 'sub_category'], name='Departments_categor_1d6388_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['payment_status'], name='Departments_payment_6f4889_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetfieldpermission',
            index=models.Index(fields=['user', 'event_department'], name='Departments_user_id_589855_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetfieldpermission',
            index=models.Index(fields=['event_department', 'field_key'], name='Departments_event_d_c1ca67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetfieldpermission',
            unique_together={('user', 'event_department', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='eventdepartmentstaffassignment',
            index=models.Index(fields=['event_department', 'user'], name='Departments_event_d_56e069_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdepartmentstaffassignment',
            unique_together={('event_department', 'user')},
        ),
    ]
