# Generated by Django 5.1.4 on 2025-11-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='approval_status',
            field=models.CharField(choices=[('rough_estimate', 'Rough Estimate'), ('shared_with_client', 'Shared with Client'), ('pending_from_family', 'Pending from Family'), ('pending_from_vendor', 'Pending from Vendor'), ('negotiation', 'Negotiation'), ('approved', 'Approved')], default='rough_estimate', help_text='Track approval progress of this line item', max_length=40),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='payment_status',
            field=models.CharField(choices=[('unbilled', 'Unbilled'), ('billed', 'Billed'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('due', 'Due'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unbilled', max_length=20),
        ),
    ]
