# Generated by Django 5.1.4 on 2025-11-14 10:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_budgetlineitem_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlineitem',
            name='exchange_rate_to_inr',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Conversion rate from item currency to INR (e.g. 83.2500 for USD → INR)', max_digits=20),
        ),
    ]
