# Generated by Django 5.1.4 on 2026-02-01 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_budgetlineitem_exchange_rate_to_inr'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModelAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The model type (Event, Guest, Session, TravelDetail, Accommodation, EventRegistration, BudgetLineItem, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_accesses', to='Departments.department')),
            ],
            options={
                'ordering': ['department', 'content_type'],
                'indexes': [models.Index(fields=['department', 'content_type'], name='Departments_departm_237719_idx')],
                'unique_together': {('department', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text="The field name (e.g., 'email', 'location', 'unit_rate')", max_length=100)),
                ('permission_type', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('read_write', 'Read & Write')], default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='The model type (Event, Guest, Session, TravelDetail, Accommodation, EventRegistration, BudgetLineItem, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to='Departments.eventdepartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_department', 'content_type', 'field_name'],
                'indexes': [models.Index(fields=['user', 'event_department'], name='Departments_user_id_984711_idx'), models.Index(fields=['event_department', 'content_type', 'field_name'], name='Departments_event_d_0196db_idx'), models.Index(fields=['content_type', 'field_name'], name='Departments_content_e864ae_idx')],
                'unique_together': {('user', 'event_department', 'content_type', 'field_name')},
            },
        ),
    ]
