# Generated by Codex on 2026-02-23

from django.db import migrations


def seed_accounts_department(apps, schema_editor):
    Department = apps.get_model("Departments", "Department")

    # Primary lookup by canonical slug.
    by_slug = Department.objects.filter(slug="accounts").first()
    if by_slug:
        if by_slug.name != "Accounts":
            by_slug.name = "Accounts"
            by_slug.save(update_fields=["name"])
        return

    # Fallback by case-insensitive name.
    by_name = Department.objects.filter(name__iexact="Accounts").first()
    if by_name:
        by_name.name = "Accounts"
        by_name.slug = "accounts"
        by_name.save(update_fields=["name", "slug"])
        return

    Department.objects.create(name="Accounts", slug="accounts")


def noop_reverse(apps, schema_editor):
    # Keep data on rollback to avoid deleting user-linked records.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("Departments", "0004_add_rbac_models"),
    ]

    operations = [
        migrations.RunPython(seed_accounts_department, noop_reverse),
    ]
