# Generated by Django 5.1.4 on 2026-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0006_eventheadassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventheadassignment',
            new_name='Departments_event_i_ed66f2_idx',
            old_name='Department_event_i_20203e_idx',
        ),
        migrations.RenameIndex(
            model_name='eventheadassignment',
            new_name='Departments_user_id_602f47_idx',
            old_name='Department_user_id_67a122_idx',
        ),
    ]
