# Generated by Django 5.1.4 on 2025-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_session_venue_alter_event_bride_name_and_more'),
        ('Guest', '0002_guest_city_guest_nationality_guest_photo_id'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_guest_fields',
            field=models.ManyToManyField(blank=True, help_text='Which Guest fields this user may view', related_name='allowed_fields_staff', to='Guest.guestfield'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_events',
            field=models.ManyToManyField(related_name='staff_users', through='Events.EventStaffAssignment', to='Events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_sessions',
            field=models.ManyToManyField(related_name='staff_users', through='Events.SessionStaffAssignment', to='Events.session'),
        ),
    ]
