# Generated by Django 5.1.4 on 2025-07-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_eventfield_sessionfield'),
        ('Staff', '0002_user_allowed_guest_fields_user_assigned_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_event_fields',
            field=models.ManyToManyField(blank=True, help_text='Which Event fields this user may view', related_name='allowed_event_fields_staff', to='Events.eventfield'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_session_fields',
            field=models.ManyToManyField(blank=True, help_text='Which Session fields this user may view', related_name='allowed_session_fields_staff', to='Events.sessionfield'),
        ),
    ]
