# Generated by Django 5.1.4 on 2025-07-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_user_allowed_event_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowed_event_fields',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allowed_guest_fields',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allowed_session_fields',
        ),
    ]
