# Generated by Django 5.1.4 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_remove_user_allowed_event_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('super_admin', 'Super Admin'), ('department_head', 'Department Head')], max_length=20),
        ),
    ]
