# Generated by Django 5.1.4 on 2026-02-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0004_add_rbac_models'),
        ('Staff', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_sessions',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this user heads (for department_head role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_heads', to='Departments.department'),
        ),
    ]
