# Generated by Codex on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Staff", "0006_update_user_model_rbac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("super_admin", "Super Admin"),
                    ("department_head", "Department Head"),
                ],
                max_length=20,
            ),
        ),
    ]
