# Generated by Django 5.1.4 on 2025-11-13 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Label for this slab set, e.g. 'FY 2024-25 New Regime'", max_length=100)),
                ('regime', models.CharField(blank=True, help_text="Optional tag for tax regime type (e.g. 'old', 'new', 'corporate')", max_length=50, null=True)),
                ('financial_year', models.CharField(blank=True, help_text="Financial year this slab applies to (e.g. '2024-25')", max_length=20, null=True)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum income for this slab (inclusive)', max_digits=12, null=True)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, help_text="Maximum income for this slab (exclusive). Leave blank for 'no upper limit'.", max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage for this slab (e.g. 5.00 for 5%)', max_digits=5)),
                ('surcharge_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional surcharge percentage applied above this slab, if any', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Slab',
                'verbose_name_plural': 'Tax Slabs',
                'ordering': ['financial_year', 'lower_limit'],
                'unique_together': {('financial_year', 'regime', 'lower_limit')},
            },
        ),
    ]
