# Generated by Django 5.1.4 on 2025-09-03 13:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0012_wasendmap_consumed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_rsvp_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='Events.event')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MessageTemplateVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variable_name', models.CharField(max_length=100)),
                ('variable_value', models.TextField(blank=True)),
                ('variable_description', models.TextField(blank=True)),
                ('variable_position', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='MessageTemplates.messagetemplate')),
            ],
            options={
                'ordering': ('variable_position', 'variable_name'),
                'unique_together': {('template', 'variable_name')},
            },
        ),
    ]
