# Generated by Django 5.1.4 on 2025-09-03 15:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_wasendmap_consumed_at_and_more'),
        ('MessageTemplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rendered_text', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_messages', to='Events.event')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_messages', to='Events.eventregistration')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MessageTemplates.messagetemplate')),
            ],
        ),
    ]
