# Generated by Django 5.1.4 on 2025-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_wasendmap_consumed_at_and_more'),
        ('MessageTemplates', '0002_queuedmessage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='queuedmessage',
            index=models.Index(fields=['registration', 'sent'], name='MessageTemp_registr_c1745c_idx'),
        ),
    ]
