# Generated by Django 5.1.4 on 2025-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0003_queuedmessage_messagetemp_registr_c1745c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media attached to this template', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='media_url',
            field=models.URLField(blank=True, help_text='WhatsApp media ID or URL', max_length=500, null=True),
        ),
    ]
