# Generated by Django 5.1.4 on 2025-12-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0004_messagetemplate_media_type_messagetemplate_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='media_url',
        ),
    ]
