# Generated by Django 5.1.4 on 2025-12-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0005_remove_messagetemplate_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='media_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business API media ID returned after upload', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media attached to this template', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='media_url',
            field=models.URLField(blank=True, help_text='Original media file URL', max_length=500, null=True),
        ),
    ]
