# Generated by Django 5.1.4 on 2026-01-14 11:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0006_messagetemplate_media_id_messagetemplate_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waba_id', models.CharField(db_index=True, help_text='WhatsApp Business Account ID from Meta', max_length=100, unique=True)),
                ('name', models.CharField(help_text="Business account name (e.g., 'ANK Wedding Services')", max_length=200)),
                ('_encrypted_token', models.TextField(blank=True, help_text='Fernet-encrypted permanent system user access token')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Business Account',
                'verbose_name_plural': 'WhatsApp Business Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(db_index=True, help_text='Phone Number ID from Meta (unique identifier)', max_length=100, unique=True)),
                ('asset_id', models.CharField(db_index=True, help_text='Asset ID from embedded signup', max_length=100)),
                ('waba_id', models.CharField(db_index=True, help_text='WABA ID (denormalized for quick lookup)', max_length=100)),
                ('display_phone_number', models.CharField(help_text="Human-readable phone number (e.g., '+919876543210')", max_length=20)),
                ('verified_name', models.CharField(help_text='Verified business name shown to customers', max_length=200)),
                ('quality_rating', models.CharField(default='UNKNOWN', help_text='Quality rating: GREEN, YELLOW, RED, UNKNOWN', max_length=20)),
                ('messaging_limit_tier', models.CharField(default='TIER_1K', help_text='Daily messaging limit tier (e.g., TIER_1K, TIER_10K, TIER_100K)', max_length=20)),
                ('_encrypted_user_token', models.TextField(blank=True, help_text='Optional per-number 60-day user token (Fernet-encrypted)')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for user token (if applicable)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this number is active and available for use')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Default number to use when none specified')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this number was used to send a message', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.ForeignKey(blank=True, help_text='Parent WABA (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='MessageTemplates.whatsappbusinessaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Phone Number',
                'verbose_name_plural': 'WhatsApp Phone Numbers',
                'ordering': ['-is_default', '-last_used_at', 'display_phone_number'],
                'indexes': [models.Index(fields=['is_active', 'is_default'], name='MessageTemp_is_acti_afd34a_idx'), models.Index(fields=['waba_id', 'is_active'], name='MessageTemp_waba_id_553d89_idx')],
            },
        ),
    ]
