# Generated by Django 5.1.4 on 2026-01-22 05:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0007_whatsappbusinessaccount_whatsappphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name (e.g. 'Newsletter Jan 22')", max_length=255)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_phone_number_id', models.CharField(db_index=True, help_text='The WABA phone number ID used to send', max_length=100)),
                ('total_recipients', models.IntegerField(default=0, help_text='Count of intended targets')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extras (filters used, etc.)')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender_phone_number_id', '-created_at'], name='MessageTemp_sender__695b0e_idx')],
            },
        ),
    ]
