# Generated by Django 5.1.4 on 2026-03-10 12:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0035_seed_system_field_catalogs'),
        ('MessageTemplates', '0008_broadcastcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_keyword', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('graph_json', models.JSONField(default=dict, help_text='React Flow JSON with nodes and edges')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('WAITING_FOR_INPUT', 'Waiting For Input'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='RUNNING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='MessageTemplates.flowblueprint')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='Events.eventregistration')),
            ],
        ),
    ]
