# Generated by Django 5.1.4 on 2026-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageTemplates', '0009_flowblueprint_flowsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='message',
        ),
        migrations.AddField(
            model_name='flowsession',
            name='error_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowsession',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='components',
            field=models.JSONField(default=list, help_text='Body, Header, Footer components'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(default='en_US', max_length=10),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(help_text='Template name from Meta dashboard', max_length=255),
        ),
    ]
