# Generated by Django 5.1.4 on 2025-06-26 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on Guest (e.g. 'email', 'address')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable (e.g. 'Email Address')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('events', models.ManyToManyField(related_name='guests', through='Events.EventRegistration', to='Events.event')),
                ('sessions', models.ManyToManyField(related_name='guests', through='Events.SessionRegistration', to='Events.session')),
            ],
        ),
    ]
