# Generated by Django 5.1.4 on 2025-07-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='photo_id',
            field=models.ImageField(blank=True, help_text='Scan or photo of guest ID (Visa/OCI etc.)', upload_to='guest_photo_ids/'),
        ),
    ]
