# Generated by Django 5.1.4 on 2025-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_guest_city_guest_nationality_guest_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='photo_id',
            field=models.ImageField(blank=True, help_text='Scan or photo of guest ID (Visa/OCI etc.)', null=True, upload_to='guest_photo_ids/'),
        ),
    ]
