from django.urls import path
from Departments.views import (
    DepartmentList,
    DepartmentDetail,
    EventDepartmentList,
    EventDepartmentDetail,
    EventDepartmentsByEventAPIView,
    EventDepartmentStaffAssignmentList,
    EventDepartmentStaffAssignmentDetail,
    StaffAssignmentsByEventDepartmentAPIView,
    BudgetLineItemList,
    BudgetLineItemDetail,
    BudgetItemsByEventDepartmentAPIView,
    BudgetFieldPermissionList,
    BudgetFieldPermissionDetail,
    FieldPermsByEventDepartmentAPIView,
    EventDepartmentUserFieldPermsAPIView,
    EventDepartmentUserFieldPermsSetAPIView,
    EventDepartmentUserFieldPermsAddAPIView,
    EventDepartmentUserFieldPermsRemoveAPIView,
    UserEventScopedDepartmentFieldAccessAPIView,
)
from Departments.rbac_views import (
    ModelPermissionList,
    ModelPermissionDetail,
    ModelPermissionsByEventDepartmentAPIView,
    ModelPermissionsByUserAPIView,
    DepartmentModelAccessList,
    DepartmentModelAccessDetail,
    DepartmentModelAccessByDepartmentAPIView,
    AvailableModelsAPIView,
    ModelFieldsAPIView,
    RBACMetadataAPIView,
)
from Departments.helper_views import (
    BulkAssignStaffToEventAPIView,
    BulkAssignPermissionsAPIView,
    BulkCreateDepartmentModelAccessAPIView,
)

urlpatterns = [
    # ─── Departments (global) ────────────────────────────────────────────────
    path("departments/", DepartmentList.as_view(), name="departments-list"),
    path(
        "departments/<uuid:pk>/", DepartmentDetail.as_view(), name="departments-detail"
    ),
    # ─── Event Departments ──────────────────────────────────────────────────
    path(
        "event-departments/",
        EventDepartmentList.as_view(),
        name="eventdepartments-list",
    ),
    path(
        "event-departments/<uuid:pk>/",
        EventDepartmentDetail.as_view(),
        name="eventdepartments-detail",
    ),
    path(
        "events/<uuid:pk>/departments/",
        EventDepartmentsByEventAPIView.as_view(),
        name="events-departments-list",
    ),
    # ─── Event Department Staff Assignments ─────────────────────────────────
    path(
        "event-department-staff/",
        EventDepartmentStaffAssignmentList.as_view(),
        name="eventdepartmentstaff-list",
    ),
    path(
        "event-department-staff/<uuid:pk>/",
        EventDepartmentStaffAssignmentDetail.as_view(),
        name="eventdepartmentstaff-detail",
    ),
    path(
        "event-departments/<uuid:pk>/staff/",
        StaffAssignmentsByEventDepartmentAPIView.as_view(),
        name="eventdepartment-staff-list",
    ),
    # ─── Budget Line Items ──────────────────────────────────────────────────
    path("budget-items/", BudgetLineItemList.as_view(), name="budgetitems-list"),
    path(
        "budget-items/<uuid:pk>/",
        BudgetLineItemDetail.as_view(),
        name="budgetitems-detail",
    ),
    path(
        "event-departments/<uuid:pk>/budget-items/",
        BudgetItemsByEventDepartmentAPIView.as_view(),
        name="eventdepartment-budgetitems-list",
    ),
    # ─── Budget Field Permissions ───────────────────────────────────────────
    path(
        "budget-field-permissions/",
        BudgetFieldPermissionList.as_view(),
        name="budgetfieldpermissions-list",
    ),
    path(
        "budget-field-permissions/<uuid:pk>/",
        BudgetFieldPermissionDetail.as_view(),
        name="budgetfieldpermissions-detail",
    ),
    path(
        "event-departments/<uuid:pk>/field-permissions/",
        FieldPermsByEventDepartmentAPIView.as_view(),
        name="eventdepartment-fieldpermissions-list",
    ),
    # ─── User-Specific Field Permissions ────────────────────────────────────
    path(
        "event-departments/<uuid:event_dept_pk>/users/<uuid:user_pk>/field-permissions/",
        EventDepartmentUserFieldPermsAPIView.as_view(),
        name="eventdepartment-user-fieldpermissions-list",
    ),
    path(
        "event-departments/<uuid:event_dept_pk>/users/<uuid:user_pk>/field-permissions/set/",
        EventDepartmentUserFieldPermsSetAPIView.as_view(),
        name="eventdepartment-user-fieldpermissions-set",
    ),
    path(
        "event-departments/<uuid:event_dept_pk>/users/<uuid:user_pk>/field-permissions/add/",
        EventDepartmentUserFieldPermsAddAPIView.as_view(),
        name="eventdepartment-user-fieldpermissions-add",
    ),
    path(
        "event-departments/<uuid:event_dept_pk>/users/<uuid:user_pk>/field-permissions/remove/",
        EventDepartmentUserFieldPermsRemoveAPIView.as_view(),
        name="eventdepartment-user-fieldpermissions-remove",
    ),
    path(
        "users/<uuid:user_pk>/events/<uuid:event_pk>/departments/field-access/",
        UserEventScopedDepartmentFieldAccessAPIView.as_view(),
        name="user-eventdept-field-access-by-event",
    ),
    # ─── RBAC: Model Permissions ────────────────────────────────────────────────
    path(
        "model-permissions/",
        ModelPermissionList.as_view(),
        name="modelpermissions-list",
    ),
    path(
        "model-permissions/<uuid:pk>/",
        ModelPermissionDetail.as_view(),
        name="modelpermissions-detail",
    ),
    path(
        "event-departments/<uuid:pk>/model-permissions/",
        ModelPermissionsByEventDepartmentAPIView.as_view(),
        name="eventdepartment-modelpermissions-list",
    ),
    path(
        "users/<uuid:pk>/model-permissions/",
        ModelPermissionsByUserAPIView.as_view(),
        name="user-modelpermissions-list",
    ),
    # ─── RBAC: Department Model Access ─────────────────────────────────────────
    path(
        "department-model-access/",
        DepartmentModelAccessList.as_view(),
        name="departmentmodelaccess-list",
    ),
    path(
        "department-model-access/<uuid:pk>/",
        DepartmentModelAccessDetail.as_view(),
        name="departmentmodelaccess-detail",
    ),
    path(
        "departments/<uuid:pk>/model-access/",
        DepartmentModelAccessByDepartmentAPIView.as_view(),
        name="department-modelaccess-list",
    ),
    # ─── RBAC: Helper Endpoints ────────────────────────────────────────────────
    path(
        "events/<uuid:event_id>/assign-staff/",
        BulkAssignStaffToEventAPIView.as_view(),
        name="events-bulk-assign-staff",
    ),
    path(
        "event-departments/<uuid:event_dept_id>/users/<uuid:user_id>/bulk-permissions/",
        BulkAssignPermissionsAPIView.as_view(),
        name="eventdepartment-user-bulk-permissions",
    ),
    path(
        "departments/<uuid:department_id>/bulk-model-access/",
        BulkCreateDepartmentModelAccessAPIView.as_view(),
        name="department-bulk-model-access",
    ),
    # ─── RBAC: Helper Endpoints ────────────────────────────────────────────────
    path(
        "rbac/available-models/",
        AvailableModelsAPIView.as_view(),
        name="rbac-available-models",
    ),
    path(
        "rbac/models/<str:model_name>/fields/",
        ModelFieldsAPIView.as_view(),
        name="rbac-model-fields",
    ),
    path(
        "rbac/metadata/",
        RBACMetadataAPIView.as_view(),
        name="rbac-metadata",
    ),
]
