# Generated by Django 5.1.4 on 2025-06-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guest'),
        ),
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Events.event'),
        ),
        migrations.AddField(
            model_name='sessionregistration',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guest'),
        ),
        migrations.AddField(
            model_name='sessionregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Events.session'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('guest', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionregistration',
            unique_together={('guest', 'session')},
        ),
    ]
