# Generated by Django 5.1.4 on 2025-07-07 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='pax',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of attendees'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='estimated_pax',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='family_salutation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='guest_group',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends')], default='friends', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='hamper_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='name_on_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='sub_guest_group',
            field=models.CharField(choices=[('family', 'Family'), ('school_friends', 'School friends'), ('college_friends', 'College friends')], default='family', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.')], max_length=5),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='visa_oci',
            field=models.FileField(blank=True, help_text='Upload visa/OCI document', upload_to='guest_visas/'),
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='entertainment',
            field=models.TextField(blank=True, help_text='Describe the entertainment planned'),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pax',
            field=models.PositiveIntegerField(default=0, help_text='Expected number of attendees in this session'),
        ),
    ]
