# Generated by Django 5.1.4 on 2025-07-08 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_bride_name_event_groom_name_event_pax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='family_salutation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='guest_group',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('friends', 'Friends')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='name_on_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='sub_guest_group',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('school_friends', 'School friends'), ('college_friends', 'College friends')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='visa_oci',
            field=models.FileField(blank=True, help_text='Upload visa/OCI document', null=True, upload_to='guest_visas/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Team Lead'), ('crew', 'Crew Member')], max_length=20)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SessionStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Session Lead'), ('crew', 'Crew Member')], max_length=20)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('removed_on', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='Events.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
    ]
