# Generated by Django 5.1.4 on 2025-07-26 23:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_session_venue_alter_event_bride_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='additional_guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExtraAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo_id', models.FileField(blank=True, null=True, upload_to='extra_attendee_ids/')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attendees', to='Events.eventregistration')),
            ],
        ),
    ]
