# Generated by Django 5.1.4 on 2025-07-27 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_eventregistration_additional_guest_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on Event (e.g. 'location', 'venue')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g. 'Venue')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on Session (e.g. 'title', 'start_time')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g. 'Session Title')", max_length=100)),
            ],
        ),
    ]
