# Generated by Django 5.1.4 on 2025-07-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_eventfield_sessionfield'),
        ('Guest', '0002_guest_city_guest_nationality_guest_photo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('event_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'event_field')},
            },
        ),
        migrations.CreateModel(
            name='UserEventGuestFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('guest_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.guestfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'guest_field')},
            },
        ),
        migrations.CreateModel(
            name='UserEventSessionFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('session_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.sessionfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'session_field')},
            },
        ),
    ]
