# Generated by Django 5.1.4 on 2025-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_usereventfieldpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='unique_string',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
