# Generated by Django 5.1.4 on 2025-08-06 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_session_unique_string'),
        ('Logistics', '0007_accommodationfield_traveldetailfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on EventRegistration (e.g. 'location', 'venue')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g. 'Venue')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventAccommodationFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logistics.accommodationfield')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'accommodation_field')},
            },
        ),
        migrations.CreateModel(
            name='UserEventEventRegistrationFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('eventregistration_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventregistrationfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'eventregistration_field')},
            },
        ),
        migrations.CreateModel(
            name='UserEventTravelDetailFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.event')),
                ('traveldetail_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logistics.traveldetailfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'traveldetail_field')},
            },
        ),
    ]
