# Generated by Django 5.1.4 on 2025-08-28 23:27

import Events.models.wa_send_map
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_eventregistration_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaSendMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_id', models.CharField(db_index=True, max_length=32)),
                ('template_wamid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('expires_at', models.DateTimeField(default=Events.models.wa_send_map.default_expiry_30d)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_send_maps', to='Events.event')),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_send_maps', to='Events.eventregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['wa_id', 'event'], name='Events_wase_wa_id_057d50_idx')],
            },
        ),
    ]
