# Generated by Django 5.1.4 on 2025-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_wasendmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasendmap',
            name='consumed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='wasendmap',
            index=models.Index(fields=['expires_at'], name='Events_wase_expires_3e4ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='wasendmap',
            index=models.Index(fields=['consumed_at'], name='Events_wase_consume_794481_idx'),
        ),
    ]
