# Generated by Django 5.1.4 on 2025-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_wasendmap_consumed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='guest_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='sub_guest_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
