# Generated by Django 5.1.4 on 2025-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_alter_eventregistration_guest_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('social', 'Social')], default='wedding', help_text='Type of event: Wedding, Corporate, or Social', max_length=20),
        ),
    ]
