# Generated by Django 5.1.4 on 2025-11-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_alter_eventregistration_guest_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='venue',
        ),
    ]
