# Generated by Django 5.1.4 on 2025-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_event_client_name_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], default='domestic', help_text='Whether the event is Domestic or International', max_length=20),
        ),
    ]
