# Generated by Django 5.1.4 on 2025-11-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_remove_session_venue'),
        ('Logistics', '0018_travelcapturesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='Logistics.hotel'),
        ),
    ]
