# Generated by Django 5.1.4 on 2025-11-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_event_location_type'),
        ('Events', '0015_session_venue'),
    ]

    operations = [
    ]
