# Generated by Django 5.1.4 on 2025-11-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_event_location_type'),
        ('Events', '0016_event_client_name_event_type'),
    ]

    operations = [
    ]
