# Generated by Django 5.1.4 on 2025-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0017_fix_duplicate_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("wedding", "Wedding"),
                    ("corporate", "Corporate"),
                    ("social", "Social"),
                ],
                default="wedding",
                help_text="Type of event: Wedding, Corporate, or Social",
                max_length=20,
            ),
        ),
    ]
