# Generated by Django 5.1.4 on 2025-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0017_fix_duplicate_client_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wasendmap',
            name='Events_wase_wa_id_057d50_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='event',
                    name='client_name',
                    field=models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('social', 'Social')], default='wedding', help_text='Type of event: Wedding, Corporate, or Social', max_length=20),
        ),
        migrations.AddField(
            model_name='wasendmap',
            name='flow_type',
            field=models.CharField(blank=True, choices=[('travel', 'Travel Capture Flow'), ('rsvp', 'RSVP Reply')], db_index=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='wasendmap',
            constraint=models.UniqueConstraint(condition=models.Q(('template_wamid__isnull', False)), fields=('template_wamid',), name='unique_template_wamid_check'),
        ),
        migrations.AddConstraint(
            model_name='wasendmap',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_type__isnull', False), ('template_wamid__isnull', True)), fields=('wa_id', 'event_registration', 'flow_type'), name='unique_wa_reg_flowtype'),
        ),
    ]
