# Generated by Django 5.1.4 on 2025-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0018_remove_wasendmap_events_wase_wa_id_057d50_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='rsvp_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending Response'), ('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='not_sent', max_length=10),
        ),
    ]
