# Generated by Django 5.1.4 on 2025-12-11 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0019_alter_eventregistration_rsvp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('content', 'Content'), ('template', 'Template'), ('rsvp', 'RSVP'), ('travel', 'Travel'), ('system', 'System')], default='content', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='sent', max_length=20)),
                ('wa_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('template_name', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='Events.eventregistration')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_registration', '-timestamp'], name='Events_conv_event_r_ac51ce_idx'), models.Index(fields=['wa_message_id'], name='Events_conv_wa_mess_4d69a3_idx')],
            },
        ),
    ]
