# Generated by Django 5.1.4 on 2025-12-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0020_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(choices=[('content', 'Content'), ('template', 'Template'), ('rsvp', 'RSVP'), ('travel', 'Travel'), ('system', 'System'), ('button', 'Button')], default='content', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='wa_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
