# Generated by Django 5.1.4 on 2025-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0021_alter_conversationmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='estimated_pax',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='hamper_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
