# Generated by Django 5.1.4 on 2025-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0022_alter_eventregistration_estimated_pax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='additional_guest_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
