# Generated by Django 5.1.4 on 2025-12-14 04:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0023_eventregistration_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wamid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('recipient_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('message_type', models.CharField(choices=[('rsvp', 'RSVP'), ('custom', 'Custom'), ('travel', 'Travel'), ('template', 'Template'), ('bulk', 'Bulk')], default='rsvp', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('event_registration_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('flow_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_id', '-sent_at'], name='Events_what_recipie_e7dc0f_idx'), models.Index(fields=['status'], name='Events_what_status_26e269_idx'), models.Index(fields=['-sent_at'], name='Events_what_sent_at_0a0724_idx'), models.Index(fields=['event_registration_id', '-sent_at'], name='Events_what_event_r_a647a5_idx'), models.Index(fields=['event_id', '-sent_at'], name='Events_what_event_i_d40d4d_idx'), models.Index(fields=['guest_id', '-sent_at'], name='Events_what_guest_i_453ec4_idx')],
            },
        ),
    ]
