# Generated by Django 5.1.4 on 2025-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0024_whatsappmessagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10),
        ),
    ]
