# Generated by Django 5.1.4 on 2025-12-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0025_whatsappmessagelog_body_whatsappmessagelog_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasendmap',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wa_send_maps', to='Events.event'),
        ),
        migrations.AlterField(
            model_name='wasendmap',
            name='event_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wa_send_maps', to='Events.eventregistration'),
        ),
    ]
