# Generated by Django 5.1.4 on 2025-12-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0026_alter_wasendmap_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
