# Generated by Django 5.1.4 on 2025-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0027_conversationmessage_media_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='whatsapp_opt_in_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='whatsapp_opt_in_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('verified', 'Verified'), ('opt_out', 'Opt Out')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='whatsapp_opt_in_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='whatsapp_opted_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
