# Generated by Django 5.1.4 on 2025-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0028_eventregistration_whatsapp_opt_in_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue_name',
            field=models.CharField(blank=True, help_text="Specific venue within the hotel (e.g., 'Grand Ballroom')", max_length=255, null=True),
        ),
    ]
