# Generated by Django 5.1.4 on 2025-12-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0029_session_venue_name'),
        ('Guest', '0003_alter_guest_address_alter_guest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('uid__isnull', False)), fields=('event', 'uid'), name='unique_uid_per_event'),
        ),
    ]
