# Generated by Django 5.1.4 on 2026-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0030_event_scoped_uid_uniqueness_v2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wasendmap',
            name='unique_wa_reg_flowtype',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='sender_phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='Phone Number ID that sent/received this message (for multi-number support)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wasendmap',
            name='sender_phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='Which of OUR phone numbers sent to this guest (for reply routing)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='sender_phone_number_id',
            field=models.CharField(blank=True, db_index=True, help_text='Phone Number ID of the sender (which of OUR numbers sent/received this)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['sender_phone_number_id', '-sent_at'], name='Events_what_sender__1259d2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['recipient_id', 'sender_phone_number_id', '-sent_at'], name='Events_what_recipie_6933a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='wasendmap',
            constraint=models.UniqueConstraint(condition=models.Q(('flow_type__isnull', False), ('template_wamid__isnull', True)), fields=('wa_id', 'sender_phone_number_id', 'event_registration', 'flow_type'), name='unique_wa_sender_reg_flowtype'),
        ),
    ]
