# Generated by Django 5.1.4 on 2026-01-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0031_remove_wasendmap_unique_wa_reg_flowtype_and_more'),
        ('MessageTemplates', '0008_broadcastcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The campaign this message belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='MessageTemplates.broadcastcampaign'),
        ),
    ]
