# Generated by Django 5.1.4 on 2026-02-20 11:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0004_add_rbac_models'),
        ('Events', '0034_force_add_missing_event_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('skill_category', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('base_daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('standard_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('documents', models.JSONField(blank=True, default=dict, help_text='Links to documents or metadata')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('soft_blocked', 'Soft Blocked'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='soft_blocked', max_length=20)),
                ('role_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_allocations', to='Departments.eventdepartment')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Manpower.freelancer')),
            ],
            options={
                'unique_together': {('freelancer', 'event_department')},
            },
        ),
        migrations.CreateModel(
            name='EventCostSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('negotiated_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('days_planned', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5)),
                ('daily_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('travel_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_costs', to='Departments.budgetlineitem')),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='Manpower.freelancerallocation')),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_category', models.CharField(max_length=100)),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('estimated_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5)),
                ('max_unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requirements', to='Departments.eventdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='MoU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secure_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('template_data', models.JSONField(default=dict, help_text='Snapshot of terms at time of issue')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='mous/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mous', to='Manpower.freelancerallocation')),
            ],
        ),
        migrations.CreateModel(
            name='PostEventAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_days_worked', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5)),
                ('extra_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('revised_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('freelancer_comments', models.TextField(blank=True)),
                ('admin_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='Manpower.freelancerallocation')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_ratings', to='Events.event')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Manpower.freelancer')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('freelancer', 'event')},
            },
        ),
    ]
