# Generated by Codex on 2026-02-23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0034_force_add_missing_event_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Manpower", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mou",
            name="access_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="mou",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posteventadjustment",
            name="freelancer_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posteventadjustment",
            name="override_negotiated_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="posteventadjustment",
            name="secure_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name="EventManpowerLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_locked", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="manpower_lock", to="Events.event")),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manpower_locks_created", to=settings.AUTH_USER_MODEL)),
                ("unlocked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manpower_locks_released", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceWorkflow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=64, unique=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payable_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=15)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("approved", "Approved"), ("payable", "Payable"), ("paid", "Paid")], default="draft", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("payable_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("paid_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="invoice_workflow", to="Manpower.posteventadjustment")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manpower_invoices", to="Events.event")),
                ("event_department", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manpower_invoices", to="Departments.eventdepartment")),
                ("freelancer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="Manpower.freelancer")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManpowerAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=120)),
                ("target_model", models.CharField(max_length=120)),
                ("target_id", models.CharField(max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manpower_audit_actions", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manpower_audit_logs", to="Events.event")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
