# Generated by Django 5.1.4 on 2026-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0002_manpower_lock_invoice_audit_and_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerallocation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
