# Generated by Django 5.1.4 on 2026-02-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0003_freelancerallocation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerallocation',
            name='is_adjustment_editable',
            field=models.BooleanField(default=False),
        ),
    ]
