# Generated by Django 5.1.4 on 2026-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0004_freelancerallocation_is_adjustment_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceworkflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('payable', 'Payable'), ('paid', 'Paid'), ('rated', 'Rated')], default='draft', max_length=20),
        ),
    ]
