# Generated by Django 5.1.4 on 2026-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0005_alter_invoiceworkflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerallocation',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceworkflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('payable', 'Payable'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
