# Generated by Django 5.1.4 on 2026-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0006_freelancerallocation_is_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='id_number',
            field=models.CharField(blank=True, help_text='PAN / Aadhar', max_length=100),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='parent_name',
            field=models.CharField(blank=True, help_text='S/o / D/o', max_length=200),
        ),
    ]
