# Generated by Django 5.1.4 on 2026-02-24 13:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0007_freelancer_address_freelancer_id_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteventadjustment',
            old_name='extra_allowances',
            new_name='actual_daily_allowance',
        ),
        migrations.AddField(
            model_name='posteventadjustment',
            name='other_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
