# Generated by Django 5.1.4 on 2026-02-24 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0008_rename_extra_allowances_posteventadjustment_actual_daily_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='signed_pdf',
        ),
        migrations.CreateModel(
            name='PostEventAdjustmentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('action_type', models.CharField(choices=[('prefill', 'Admin Pre-fill'), ('submission', 'Freelancer Submission'), ('dispute', 'Admin Dispute'), ('approval', 'Final Approval')], max_length=20)),
                ('actual_days_worked', models.DecimalField(decimal_places=1, max_digits=5)),
                ('actual_daily_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('other_adjustments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('override_negotiated_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revised_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='Manpower.posteventadjustment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
