# Generated by Django 5.1.4 on 2026-02-28 09:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0034_force_add_missing_event_fields'),
        ('Manpower', '0009_remove_mou_signed_pdf_posteventadjustmentrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_breakfast_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_lunch_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_dinner_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manpower Settings',
                'verbose_name_plural': 'Manpower Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='manpowerauditlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='manpowerauditlog',
            name='target_model',
        ),
        migrations.CreateModel(
            name='AllocationDailyMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_worked', models.BooleanField(default=True)),
                ('breakfast_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('lunch_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('dinner_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('breakfast_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lunch_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dinner_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('action', models.CharField(max_length=120)),
                ('target_model', models.CharField(max_length=120)),
                ('target_id', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='Manpower.freelancerallocation')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower_audit_logs', to='Events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
