# Generated by Django 5.1.4 on 2026-02-28 09:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0009_remove_mou_signed_pdf_posteventadjustmentrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_breakfast_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_lunch_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('default_dinner_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manpower Settings',
                'verbose_name_plural': 'Manpower Settings',
            },
        ),
        migrations.CreateModel(
            name='AllocationDailyMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_worked', models.BooleanField(default=True)),
                ('breakfast_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('lunch_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('dinner_type', models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance')], default='allowance', max_length=20)),
                ('breakfast_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lunch_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dinner_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='Manpower.freelancerallocation')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('allocation', 'date')},
            },
        ),
    ]
