# Generated by Django 5.1.4 on 2026-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0010_manpowersettings_allocationdailymeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationdailymeal',
            name='breakfast_type',
            field=models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance'), ('cash', 'Cash (Paid on Spot)')], default='allowance', max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationdailymeal',
            name='dinner_type',
            field=models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance'), ('cash', 'Cash (Paid on Spot)')], default='allowance', max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationdailymeal',
            name='lunch_type',
            field=models.CharField(choices=[('crew_meal', 'Crew Meal'), ('allowance', 'Allowance'), ('cash', 'Cash (Paid on Spot)')], default='allowance', max_length=20),
        ),
    ]
