# Generated by Django 5.1.4 on 2026-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0034_force_add_missing_event_fields'),
        ('Manpower', '0011_alter_allocationdailymeal_breakfast_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequirement',
            name='sessions',
            field=models.ManyToManyField(blank=True, help_text='Sessions this requirement is applicable for', related_name='manpower_requirements', to='Events.session'),
        ),
    ]
