# Generated by Django 5.1.4 on 2026-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0012_manpowerrequirement_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequirement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequirement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
