# Generated by Django 5.1.4 on 2026-03-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0013_manpowerrequirement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerallocation',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='Manpower.manpowerrequirement'),
        ),
    ]
