# Generated by Django 5.1.4 on 2026-03-07 09:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0014_freelancerallocation_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteventadjustment',
            old_name='actual_daily_allowance',
            new_name='travel_adjustments',
        ),
        migrations.RemoveField(
            model_name='eventcostsheet',
            name='daily_allowance',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='standard_allowance',
        ),
        migrations.RemoveField(
            model_name='posteventadjustmentrevision',
            name='actual_daily_allowance',
        ),
        migrations.AddField(
            model_name='posteventadjustmentrevision',
            name='travel_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
