# Generated by Django 5.1.4 on 2026-03-07 10:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0015_rename_actual_daily_allowance_posteventadjustment_travel_adjustments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventadjustment',
            name='engagement_periods',
            field=models.JSONField(blank=True, default=list, help_text="List of periods: [{'start': 'YYYY-MM-DD', 'end': 'YYYY-MM-DD', 'days': 1.0}]"),
        ),
        migrations.AddField(
            model_name='posteventadjustment',
            name='total_engagement_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Sum of days from all engagement periods for rate calculation', max_digits=5),
        ),
        migrations.AddField(
            model_name='posteventadjustmentrevision',
            name='engagement_periods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='posteventadjustmentrevision',
            name='total_engagement_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='posteventadjustment',
            name='actual_days_worked',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Used for meal allowance calculations (set number of days)', max_digits=5),
        ),
    ]
