# Generated by Django 5.1.4 on 2026-03-07 12:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0016_posteventadjustment_engagement_periods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceworkflow',
            name='secure_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posteventadjustmentrevision',
            name='actual_meal_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
