# Generated by Django 5.1.4 on 2026-03-07 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0017_invoiceworkflow_secure_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceworkflow',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
