# Generated by Django 5.1.4 on 2026-03-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0018_alter_invoiceworkflow_secure_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='id_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('AADHAR', 'Aadhar')], default='PAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='id_number',
            field=models.CharField(blank=True, help_text='PAN / Aadhar Number', max_length=100),
        ),
    ]
