# Generated by Django 5.1.4 on 2026-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0019_freelancer_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerallocation',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpowerrequirement',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
