# Generated by Django 5.1.4 on 2026-03-07 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0020_freelancerallocation_is_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skill_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manpowerrequirement',
            name='skill_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancers', to='Manpower.skill'),
        ),
        migrations.AddField(
            model_name='manpowerrequirement',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='Manpower.skill'),
        ),
    ]
