# Generated by Django 5.1.6 on 2026-04-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0021_skill_alter_freelancer_skill_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='skill',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='Manpower.skill'),
        ),
    ]
