# Generated by Django 5.1.6 on 2026-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0022_remove_freelancer_skill_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequirement',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
