# Generated by Django 5.1.4 on 2026-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0007_rename_department_event_i_20203e_idx_departments_event_i_ed66f2_idx_and_more'),
        ('Manpower', '0024_manpowerrequirement_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freelancerallocation',
            unique_together={('freelancer', 'event_department', 'requirement')},
        ),
    ]
