# Generated by Django 5.1.6 on 2026-06-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0027_freelancerallocation_last_name_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='teams',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='freelancerallocation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequirement',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequirement',
            name='teams',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
