# Generated by Django 5.1.4 on 2025-12-18 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


def cleanup_old_tables(apps, schema_editor):
    """Drop old CustomField tables if they exist (handles production deployment)"""
    with schema_editor.connection.cursor() as cursor:
        # Drop old tables if they exist (works for both SQLite and PostgreSQL)
        cursor.execute("DROP TABLE IF EXISTS CustomField_customfieldvalue")
        cursor.execute("DROP TABLE IF EXISTS CustomField_customfielddefinition")
        # Clean up old migration records
        cursor.execute("DELETE FROM django_migrations WHERE app = 'CustomField'")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0027_conversationmessage_media_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # First, clean up any old tables from previous schema
        migrations.RunPython(cleanup_old_tables, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name (e.g. 'speaker_bio')", max_length=100)),
                ('label', models.CharField(help_text="Human‐readable label (e.g. 'Speaker Bio')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('help_text', models.CharField(blank=True, help_text='Optional help text', max_length=300)),
                ('content_type', models.ForeignKey(help_text='The model this custom field applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(help_text='The event this custom field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='Events.event')),
            ],
            options={
                'unique_together': {('event', 'content_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),
                ('value', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='CustomField.customfielddefinition')),
            ],
            options={
                'unique_together': {('definition', 'content_type', 'object_id')},
            },
        ),
    ]
