# Generated by Django 5.1.4 on 2025-12-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomField', '0001_initial'),
        ('Events', '0027_conversationmessage_media_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event this custom field belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='Events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='customfielddefinition',
            unique_together={('event', 'content_type', 'name')},
        ),
    ]
