# Generated by Django 5.1.4 on 2025-12-19 03:35

from django.db import migrations
import django.db.models.deletion
import uuid
from django.db import models


def fix_object_id_schema(apps, schema_editor):
    """
    Fix object_id field type from integer to varchar(36) to support UUIDs.
    This migration drops and recreates the CustomField tables with correct schema.
    """
    db_vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        # Drop existing tables (they have wrong schema with integer object_id)
        # Use CASCADE for PostgreSQL, but not for SQLite (which doesn't support it)
        if db_vendor == 'postgresql':
            cursor.execute("DROP TABLE IF EXISTS \"CustomField_customfieldvalue\" CASCADE")
            cursor.execute("DROP TABLE IF EXISTS \"CustomField_customfielddefinition\" CASCADE")
        else:  # SQLite
            cursor.execute("DROP TABLE IF EXISTS CustomField_customfieldvalue")
            cursor.execute("DROP TABLE IF EXISTS CustomField_customfielddefinition")


class Migration(migrations.Migration):

    dependencies = [
        ('CustomField', '0001_initial'),
        ('Events', '0027_conversationmessage_media_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Drop old tables with incorrect schema
        migrations.RunPython(fix_object_id_schema, reverse_code=migrations.RunPython.noop),

        # Recreate CustomFieldDefinition with correct schema
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name (e.g. 'speaker_bio')", max_length=100)),
                ('label', models.CharField(help_text="Human‐readable label (e.g. 'Speaker Bio')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('help_text', models.CharField(blank=True, help_text='Optional help text', max_length=300)),
                ('content_type', models.ForeignKey(help_text='The model this custom field applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(help_text='The event this custom field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='Events.event')),
            ],
            options={
                'unique_together': {('event', 'content_type', 'name')},
            },
        ),

        # Recreate CustomFieldValue with VARCHAR object_id (supports UUIDs)
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=36)),  # THIS IS THE FIX - VARCHAR instead of INTEGER
                ('value', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='CustomField.customfielddefinition')),
            ],
            options={
                'unique_together': {('definition', 'content_type', 'object_id')},
            },
        ),
    ]
