# Generated by Django 5.1.4 on 2025-07-08 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0004_session_venue_alter_event_bride_name_and_more'),
        ('Guest', '0002_guest_city_guest_nationality_guest_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('types_of_rooms', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_count', models.PositiveIntegerField(default=1)),
                ('room_type', models.CharField(max_length=100)),
                ('bed_type', models.CharField(max_length=100)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('rooming_remarks', models.TextField(blank=True)),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Events.eventregistration')),
                ('session_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Events.sessionregistration')),
                ('sharing_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_accommodations', to='Guest.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Logistics.hotel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_registration__isnull', False), ('session_registration__isnull', True)), models.Q(('event_registration__isnull', True), ('session_registration__isnull', False)), _connector='OR'), name='accommodation_one_registration_required')],
            },
        ),
        migrations.CreateModel(
            name='TravelDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival', models.CharField(choices=[('commercial', 'Commercial'), ('local_pickup', 'Local Pickup'), ('self', 'Self')], max_length=20)),
                ('arrival_date', models.DateField()),
                ('arrival_details', models.TextField(blank=True)),
                ('arrival_time', models.TimeField()),
                ('hotel_arrival_time', models.TimeField(blank=True, null=True)),
                ('hotel_departure_time', models.TimeField(blank=True, null=True)),
                ('return_travel', models.BooleanField(default=False)),
                ('departure', models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('local_pickup', 'Local Pickup'), ('self', 'Self')], max_length=20)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_details', models.TextField(blank=True)),
                ('event_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='Events.eventregistration')),
                ('session_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='Events.sessionregistration')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_registration__isnull', False), ('session_registration__isnull', True)), models.Q(('event_registration__isnull', True), ('session_registration__isnull', False)), _connector='OR'), name='travel_one_registration_required')],
            },
        ),
    ]
