# Generated by Django 5.1.4 on 2025-07-26 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_eventregistration_additional_guest_count_and_more'),
        ('Guest', '0002_guest_city_guest_nationality_guest_photo_id'),
        ('Logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accommodation',
            name='accommodation_one_registration_required',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='event_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='extra_attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Events.extraattendee'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='event_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='Events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('Train', 'Train'), ('Car', 'Car')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='accommodation',
            constraint=models.CheckConstraint(condition=models.Q(('extra_attendee__isnull', False), models.Q(('extra_attendee__isnull', True), ('event_registration__isnull', False), ('session_registration__isnull', True)), models.Q(('event_registration__isnull', True), ('session_registration__isnull', False)), _connector='OR'), name='accommodation_extraattendee_or_one_registration'),
        ),
    ]
