# Generated by Django 5.1.4 on 2025-07-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_eventfield_sessionfield'),
        ('Logistics', '0002_remove_accommodation_accommodation_one_registration_required_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traveldetail',
            name='travel_one_registration_required',
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='extra_attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='Events.extraattendee'),
        ),
        migrations.AddConstraint(
            model_name='traveldetail',
            constraint=models.CheckConstraint(condition=models.Q(('extra_attendee__isnull', False), models.Q(('extra_attendee__isnull', True), ('event_registration__isnull', False), ('session_registration__isnull', True)), models.Q(('event_registration__isnull', True), ('session_registration__isnull', False)), _connector='OR'), name='travel_details_extraattendee_or_one_registration'),
        ),
    ]
