# Generated by Django 5.1.4 on 2025-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_usereventfieldpermission_and_more'),
        ('Logistics', '0003_remove_traveldetail_travel_one_registration_required_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accommodation',
            name='accommodation_extraattendee_or_one_registration',
        ),
        migrations.RemoveConstraint(
            model_name='traveldetail',
            name='travel_details_extraattendee_or_one_registration',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='event_registration',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='extra_attendee',
        ),
        migrations.RemoveField(
            model_name='traveldetail',
            name='event_registration',
        ),
        migrations.RemoveField(
            model_name='traveldetail',
            name='extra_attendee',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='event_registrations',
            field=models.ManyToManyField(blank=True, related_name='accommodation_assignments', to='Events.eventregistration'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='extra_attendees',
            field=models.ManyToManyField(blank=True, related_name='accommodation_assignments', to='Events.extraattendee'),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='event_registrations',
            field=models.ManyToManyField(blank=True, related_name='travel_detail_assignments', to='Events.eventregistration'),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='extra_attendees',
            field=models.ManyToManyField(blank=True, related_name='travel_detail_assignments', to='Events.extraattendee'),
        ),
    ]
