# Generated by Django 5.1.4 on 2025-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0004_remove_accommodation_accommodation_extraattendee_or_one_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='traveldetail',
            old_name='event_id',
            new_name='event',
        ),
    ]
