# Generated by Django 5.1.4 on 2025-08-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0005_rename_event_id_accommodation_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetail',
            name='airline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='pnr',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
