# Generated by Django 5.1.4 on 2025-08-06 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0006_traveldetail_airline_traveldetail_flight_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on Accommodation (e.g. 'location', 'venue')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g. 'Venue')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelDetailField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Exact field name on TravelDetail (e.g. 'location', 'venue')", max_length=50, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g. 'Venue')", max_length=100)),
            ],
        ),
    ]
