# Generated by Django 5.1.4 on 2025-08-07 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0010_eventregistration_created_at_and_more"),
        ("Logistics", "0008_traveldetail_created_at_traveldetail_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="types_of_rooms",
        ),
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="location",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="EventHotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_hotels",
                        to="Events.event",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_hotels",
                        to="Logistics.hotel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accommodation",
            name="event_hotel",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodations",
                to="Logistics.eventhotel",
            ),
        ),
        migrations.CreateModel(
            name="EventHotelRoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_type", models.CharField(max_length=100)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("available_count", models.PositiveIntegerField(default=0)),
                (
                    "event_hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="Logistics.eventhotel",
                    ),
                ),
            ],
            options={
                "unique_together": {("event_hotel", "room_type")},
            },
        ),
    ]
