# Generated by Django 5.1.4 on 2025-08-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0009_remove_accommodation_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='event_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Logistics.eventhotel'),
        ),
    ]
