# Generated by Django 5.1.4 on 2025-09-01 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_wasendmap_consumed_at_and_more'),
        ('Logistics', '0010_alter_accommodation_event_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhotelroomtype',
            old_name='total_count',
            new_name='allocation_count',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='mumbai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='india', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eventhotel',
            unique_together={('event', 'hotel')},
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='Logistics.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventhotelroomtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventhotelroomtype',
            name='hotel_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_room_types', to='Logistics.hotelroomtype'),
        ),
        migrations.AlterUniqueTogether(
            name='eventhotelroomtype',
            unique_together={('event_hotel', 'hotel_room_type')},
        ),
        migrations.RemoveField(
            model_name='eventhotelroomtype',
            name='room_type',
        ),
    ]
