# Generated by Django 5.1.4 on 2025-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0011_rename_total_count_eventhotelroomtype_allocation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetail',
            name='departure_airline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='departure_flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traveldetail',
            name='departure_pnr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetail',
            name='pnr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
