# Generated by Django 5.1.4 on 2025-09-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0012_traveldetail_departure_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetail',
            name='arrival',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('local_pickup', 'Local Pickup'), ('self', 'Self')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetail',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetail',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
