# Generated by Django 5.1.4 on 2025-09-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0013_alter_traveldetail_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetail',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
