# Generated by Django 5.1.4 on 2025-09-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0014_traveldetail_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='room_type',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='event_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accommodations', to='Logistics.eventhotelroomtype'),
        ),
    ]
