# Generated by Django 5.1.4 on 2025-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0015_remove_accommodation_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
