# Generated by Django 5.1.4 on 2025-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0016_alter_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetail',
            name='departure_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
