# Generated by Django 5.1.4 on 2025-09-19 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_alter_eventregistration_guest_group_and_more'),
        ('Logistics', '0017_alter_traveldetail_departure_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField(default=dict)),
                ('step', models.CharField(default='opt_in', max_length=64)),
                ('last_prompt_step', models.CharField(blank=True, default='', max_length=64)),
                ('is_complete', models.BooleanField(default=False)),
                ('last_msg_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_capture', to='Events.eventregistration')),
            ],
        ),
    ]
