# Generated by Django 5.1.4 on 2025-11-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0018_travelcapturesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldetail',
            name='source_departure_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
