# Generated by Django 5.1.4 on 2025-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0019_traveldetail_source_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhotelroomtype',
            name='allocation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventhotelroomtype',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
    ]
