# Generated by Django 5.1.4 on 2025-11-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0020_alter_eventhotelroomtype_allocation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_venue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='venue_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
