# Generated by Django 5.1.6 on 2026-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0024_traveldetail_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='has_disabled_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='is_interconnecting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='is_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='is_twin_sharing',
            field=models.BooleanField(default=False),
        ),
    ]
