# Generated by Django 5.1.6 on 2026-07-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0025_hotelroomtype_has_disabled_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='event_room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Logistics.eventhotelroomtype'),
        ),
    ]
